### ISSUE TITLE
Issue with windows configuration

### ISSUE THREAD

**Issue by mibdragon82** [tfatykhov/WinkRedNode#17]
Hi, I've been trying to get this up and running, but haven't had any luck, hopeful reporting an issue is the way to go, I couldn't find an email address to contact. I've been able to get Node-red installed, Freeboard, and Winkboard. The only trouble I am having is Winkboard loads, and I can tell it's pulling all of my devices, but it's not pulling their state, they all load blank. It even loads the main Freeboard options for a second, but then they disappear. I've tried reloading the configuration, adjusting my external connection string and port, but just can't get it to work. Freeboard itself will work if I try to load it without Winkboard.

![2016-01-11 22_07_21-winkboard by groups](https://cloud.githubusercontent.com/assets/16659997/12254575/d3b9e146-b8af-11e5-808f-48707dd487aa.png)

Any help would be appreciated, thanks.

**Comment by mifbody** [comment]
Hi,

In your bluemix-settings file for the base URL, do you have https:// or http:// ? Typically if your bluemix-settings says https:// and then you use http:// (or vice versa) you'll get these blank stats. As a quick test, you could try using https://localhost:1880/freeboard/winkboard and see if that works

**Comment by tfatykhov** [comment]
Hi, also you need to make sure that your local computer can be accessed from outside internet. node-red app using web hooks so status updates are initiated by wink servers as http(s) posts  to your node-red application. Also open a node-red editor and check debug tab on the right side for any errors, etc. 

also there is FB group where we have long discussion about wink and node-red - https://www.facebook.com/groups/WinkUsersGroup/permalink/704053843033339/

**Comment by mibdragon82** [comment]
Thanks for the quick responses. I'm actually using the local windows installation method but I may give the Bluemix version a try. So I have modified the local "settings.js" with the appropriate settings. Here is what I have:

```
functionGlobalContext: {
    WinkUser         : { uid : "username@wink.com"
                         , pwd : "**********"
                         }
    , BlueMixUrlBase   : "http://mydynamicdns:53000/"
    , forecastIoApiKey : "your API key"
    , HomeLocation     : { lon : "the longitude of your home location"
                         , lat : "the lattitude of your home location"
                         }
    , FREEBOARD_TOKEN  : "alksjdlafjlffp29r284u9248098euwruewioru234"
    , IFTTT_TOKEN: "***************************"
    , motionAdjustTstat: true
},
```

I have 53000 from the outside directed to the default port internally, 1880. Wink info is my username and password. I did not sign up for a forecast key yet nor setup the Lon or Lat. Freeboard token was a generic string I added. IFTTT token I pulled from my account on the maker channel. I can access both the Node-red and the Winkboard externally. The only thing that seems out of the oridinary is that if I try a different browser such as Internet Explorer, it prompts to continue due to a certificate error and then hangs.

From what I can tell, everything seems like it is working correctly unless I have the port down wrong.

![2016-01-12 20_22_10-c__users_administrator_appdata_roaming_npm_node_modules_node-red_settings js - n](https://cloud.githubusercontent.com/assets/16659997/12283226/3d983328-b96a-11e5-83f8-1d420697541a.png)

![2016-01-12 20_16_53-c__users_administrator_appdata_roaming_npm_node_modules_node-red_settings js - n](https://cloud.githubusercontent.com/assets/16659997/12283124/982aa9b6-b969-11e5-8e84-1ca66f9b1d9d.png)

Thanks.

**Comment by tfatykhov** [comment]
remove "/" from the end of BlueMixUrlBase  it should be: http://mydynamicdns:53000
also make sure you can access http://mydynamicdns:53000 internally and externally. Should be if you set up port forwarding properly, so just a troubleshooting step.

**Comment by tfatykhov** [comment]
Also - you need to update package.json (steps defined here - https://github.com/tfatykhov/WinkRedNode/blob/master/README-Local-Windows.md) so it will get modified version of freeboard from my github repository and for that, since you are using windows, you need to install github client from here - https://desktop.github.com/

**Comment by mibdragon82** [comment]
Excellent, removing the "/" worked, it is now loading and detecting the state of the devices. I still need to modify the package.json then. I actually already have the github installed because I was having an issue with another package automatically installing. I tried to troubleshoot as much as i could before opening a ticket. I thought about removing the "/" initially, but it looked like it was needed. I didn't even notice it wasn't in the Bluemix instructions. Thanks for all the help.

**Comment by tfatykhov** [comment]
Glad it works and yes, you are correct, instructions are bit outdated and probably not 100% clear. I will try to update them as soon as I can. Thanks for opening this - it will help others!
