### ISSUE TITLE
bug on configuration page

### ISSUE THREAD

**Issue by tfatykhov** [tfatykhov/WinkRedNode#19]
if settings from bluemix-settings.js are not uncommented config tab ignores them.

**Comment by sethhere04** [comment]
which line needs to be uncommented?

**Comment by tfatykhov** [comment]
Basically you need to add all setting even with blank values that are on config tab . once you have it in bluemix-settings,js and restart node-red app - you can update them via configuration tab. I will fix that over weekend.

**Comment by tfatykhov** [comment]
fixed. no need to add in both places for bluemix instance. Still need to do that for local
