### ISSUE TITLE
details tab sometimes does not show lights in groups widgets

### ISSUE THREAD

**Issue by tfatykhov** [tfatykhov/WinkRedNode#20]
need to look at it. running initialization flow fixes it. Probably caching with E-tag is an issue.

**Comment by mifbody** [comment]
I believe the initialization flow sometimes needs to be ran 2 times - especially on application start up. First run it grabs all the group names and all the devices, 2nd run it actually inputs the devices into the groups.

**Comment by tfatykhov** [comment]
you probably correct. I will try to put delay so it grabs groups first.

**Comment by tfatykhov** [comment]
fixed in latest update
