### ISSUE TITLE
add occupancy icon/feature for ecobee3 thermostat

### ISSUE THREAD

**Issue by jovantrajceski** [tfatykhov/WinkRedNode#33]
Hi,  i have noticed that the ecobee thermostat displays  temperature but not occupancy - can we add occupancy status please the same way as remote sensors already have.  thanks.

**Comment by tfatykhov** [comment]
Do you mean details tab?

**Comment by jovantrajceski** [comment]
Yes - thanks

**Comment by jovantrajceski** [comment]
second note (if i may) :-)  - is it possible to add ecobee occupancy icon on summary page with a count of occupaid rooms (i.e. 1 out of 10)

**Comment by tfatykhov** [comment]
This is done
