### ISSUE TITLE
Add occupancy icon on summary page for ecobee 

### ISSUE THREAD

**Issue by jovantrajceski** [tfatykhov/WinkRedNode#36]
is it possible to add ecobee occupancy icon on summary page with a count of occupied rooms (i.e. 1 out of 10) 

:-)

**Comment by tfatykhov** [comment]
Brian, Did you add that to details. I think you did but I do not have ecobee to test.

**Comment by mifbody** [comment]
Not yet, I haven't had time to do much with mine lately. Should have time
this weekend.

**Comment by tfatykhov** [comment]
Ecobee data is on the details tab. Summary may not be a good idea since we have gloval occupancy there and Ecobee is not global. Close for now.
