### ISSUE TITLE
Weather section on summary

### ISSUE THREAD

**Issue by jovantrajceski** [tfatykhov/WinkRedNode#38]
suggestions:
- have only 2 icons with one liner: Today {icon] cloudy, Tomorrow [icon] rain
- if you click any of those 2 it takes you to new weather tab or maybe little [+] sign that takes you to weather tab
- the detailed weather tab can be like a widget or more detailed , re; http://blog.forecast.io/forecast-embeds/

**Comment by tfatykhov** [comment]
sounds good. I had similar thing in mind.

**Comment by tfatykhov** [comment]
new approach as of UI 2.0. weather card and forecast in modal.
