### ISSUE TITLE
Push Notifications to Android

### ISSUE THREAD

**Issue by bigverm23** [tfatykhov/WinkRedNode#42]
sending notifications to android phone

**Comment by tfatykhov** [comment]
Could you please tell more about how you envision this? same stuff that you have in events log?

**Comment by bigverm23** [comment]
would be interesting to received android notifications when an action takes place i.e. lights turn on, doors open, etc...noticed there is a pushbullet node under mobile...if i knew where to place this that might do it.

**Comment by tfatykhov** [comment]
I can add option to send data via pushbullet for same stuff I am sending to UI log for a start. I actually did it for testing some time ago so should not be a big deal.

**Comment by bigverm23** [comment]
sounds good to me!  let me know if I can help

**Comment by tfatykhov** [comment]
This is done in latest update.
