### ISSUE TITLE
Case correction in tabletUI.json

### ISSUE THREAD

**Issue by dawseyt** [tfatykhov/WinkRedNode#44]
Not sure if this affects everyone or just me, but whenever I deploy updated tabletUI.json, I have to correct the case of "**mysummary**" in the following line in the tabletUI.json:

```
  `<iframe frameBorder="0" seamless="seamless" allowtransparency="true" id="Iframe0" src="mysummary" width="100%"></iframe>
```

The summary iframe does not load for me until I change it to "**MySummary**"

**Comment by mifbody** [comment]
(BMeissen) I haven't experienced this issue - could you give details on
what O/S and browser you're using? Have you tried using a different browser
to see if it's a browser specific issue?

**Comment by tfatykhov** [comment]
This could be a cache issue. Node.js https server is not case sensitive for urls. Could you clear cache? also could you specify OS and Browser that you are using?

**Comment by dawseyt** [comment]
Hi Brian,

Haven't checked with another browser. I cleared the cache and same thing.
I'm using the latest Chrome build on Windows 7. Not really a big deal, just
thought I'd mention it in case others are seeing the same thing and it was
an easy fix.

**Comment by tfatykhov** [comment]
I am using chrome as well with win 8 and 10 and never had this problem. node.js server app is not case sensitive for urls and nobody else reported this issue so far. I will probably make everything lowercase

**Comment by mifbody** [comment]
Are you still having this issue? As Timur mentioned I haven't seen anyone else have this issue, and I know firsthand that Chrome's cache is an extreme pain in the arse to really clear. For me, I had to open a new Incognito window and then view a page before my cache would actually clear out.

**Comment by dawseyt** [comment]
If it's not happening for anyone else I see no reason to change anything. I
can fix it on my end if needed. I just wanted to let you know what was
happening just in case it came up for others.  Thanks again for looking
into this and for all the great work you guys are doing.

**Comment by mifbody** [comment]
Are you running Node Red in IBM BlueMix or locally? Do you know which versions of Node Red and Node.js is being used?

**Comment by dawseyt** [comment]
I'm running the latest version on Bluemix. Come to think of it. The last
time I updated the flows, I didn't have a problem with the case. It was
just the few times before.

**Comment by mifbody** [comment]
Ok cool, maybe an old version updated or cache got unstuck. :)

**Comment by tfatykhov** [comment]
So I am closing this as nobody else reported it. Thanks!
