### ISSUE TITLE
Lyric Thermostat Integration

### ISSUE THREAD

**Issue by Spaarky1978** [tfatykhov/WinkRedNode#46]
Currently the Lyric Thermostat uses its own app that is seperate from all the other apps. It has absolutely no integration with any other smart home devices. 

https://developer.honeywell.com/content/getting-started-guide

https://developer.honeywell.com/api-methods

**Comment by scambo00** [comment]
see WinkRedNode/Flows/HoneywellLryic/HoneyLyricFlow.json

**Comment by scambo00** [comment]
see WinkRedNode/Flows/HoneywellLryic/HoneyLyricFlow.json
